.PHONY: read_file

read_file:
	gcc -Wall -o read_file read_file.c -I ../src -L ../target/debug \
	    -I ../src/lib -lpm -lreadline -lpthread -ldl -lc 

str_readfile:
	gcc -Wall -o str_readfile str_readfile.c -I ../src -L ../target/debug \
	    -I ../src/lib -lpm -lreadline -lpthread -ldl -lc 
